# Generated by Django 4.2.2 on 2024-02-01 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefhgigklm93801', length=10, max_length=20, prefix='bann', primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='banner_images')),
            ],
        ),
        migrations.CreateModel(
            name='categoryModel',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefhgigklm93801', length=10, max_length=20, prefix='cat', primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='categories_images')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefhgigklm93801', length=10, max_length=20, prefix='hom', primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='houses_images')),
                ('salary', models.FloatField(verbose_name=0.0)),
                ('favorit', models.BooleanField(default=False)),
                ('location', models.TextField(default='Beni-Seuf')),
                ('discount', models.FloatField(default=0.0)),
                ('level', models.IntegerField(default=0)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('area', models.FloatField(default=0.0)),
                ('description', models.CharField(default='null', max_length=50)),
                ('conditions', models.TextField(default='null')),
                ('ava', models.CharField(default='null', max_length=100)),
                ('rev', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('viewer', models.FloatField(default=0.0)),
                ('video', models.FileField(default='null', upload_to='vedios_house')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefhgigklm93801', length=10, max_length=20, prefix='pro', primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=1000)),
                ('bio', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='user_images')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefhgigklm93801', length=10, max_length=20, prefix='eae', primary_key=True, serialize=False)),
                ('messages', models.CharField(max_length=100000)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reciever', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recieved_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Message',
                'ordering': ['timestamp'],
            },
        ),
    ]
