# Generated by Django 5.0.1 on 2024-02-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_banner_categorymodel_house_userprofile_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_translate', models.TextField()),
                ('target_language', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='messages',
            field=models.TextField(max_length=100000),
        ),
    ]
