# Generated by Django 4.2.2 on 2024-02-29 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_translatedtext_alter_chatmessage_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('rent_start_time', models.DateTimeField(auto_now_add=True)),
                ('rent_finish_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('username', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('rent_start_time', models.DateField()),
                ('rent_finish_time', models.DateField()),
                ('price', models.FloatField()),
                ('favorit', models.BooleanField(default=False)),
                ('location', models.TextField(default='Beni-Seuf')),
                ('discount', models.FloatField(default=0.0)),
                ('level', models.IntegerField(default=0)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('area', models.FloatField(default=0.0)),
                ('description', models.CharField(default='null', max_length=50)),
                ('conditions', models.TextField(default='null')),
                ('ava', models.CharField(default='null', max_length=100)),
                ('rev', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('viewer', models.FloatField(default=0.0)),
                ('video', models.FileField(default='null', null=True, upload_to='vedios_house')),
            ],
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('images', models.ImageField(blank=True, null=True, upload_to='imageee/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('images', models.ImageField(blank=True, null=True, upload_to='imagggeee/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('requestt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_comments', to='accounts.request')),
            ],
        ),
    ]
