# Generated by Django 4.2.2 on 2024-02-29 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_addoffer_offer_request_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='area',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='ava',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='favorit',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='furnished',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='level',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='rev',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='video',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='viewer',
        ),
    ]
