# Generated by Django 4.2.2 on 2024-02-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_addoffer_rent_finish_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='offer_images/'),
        ),
    ]
