# Generated by Django 4.2.2 on 2024-02-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_offer_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(default='null', upload_to='houses_images'),
        ),
        migrations.AlterField(
            model_name='house',
            name='salary',
            field=models.FloatField(default=0.0),
        ),
    ]
