# Generated by Django 4.2.2 on 2024-02-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_offer_area_offer_ava_offer_bathrooms_offer_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addoffer',
            name='rent_finish_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addoffer',
            name='rent_start_time',
            field=models.DateField(),
        ),
    ]
