# Generated by Django 4.2.2 on 2024-02-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_offer_area_remove_offer_ava_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='area',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='offer',
            name='ava',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='offer',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='conditions',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='offer',
            name='favorit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='location',
            field=models.TextField(default='Beni-Seuf'),
        ),
        migrations.AddField(
            model_name='offer',
            name='rev',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='video',
            field=models.FileField(default='null', null=True, upload_to='vedios_house'),
        ),
        migrations.AddField(
            model_name='offer',
            name='viewer',
            field=models.FloatField(default=0.0),
        ),
    ]
