# Generated by Django 4.2.2 on 2024-03-03 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_offer_area_remove_offer_ava_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='requestt',
            new_name='requests',
        ),
    ]
