# Generated by Django 4.2.2 on 2024-03-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_requestt_comment_requests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='CommentModels',
        ),
        migrations.RenameModel(
            old_name='offer',
            new_name='OfferModels',
        ),
    ]
