# Generated by Django 4.2.2 on 2024-03-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rename_comment_commentmodels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offermodels',
            name='username',
        ),
    ]
