# Generated by Django 4.2.2 on 2024-03-12 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodels',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.house'),
        ),
    ]
