# Generated by Django 4.2.2 on 2024-03-13 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_offermodels_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offermodels',
            name='house',
        ),
        migrations.AlterField(
            model_name='offermodels',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
