# Generated by Django 4.2.2 on 2024-03-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_offermodels_house_alter_offermodels_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodels',
            name='area',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='offermodels',
            name='ava',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='offermodels',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offermodels',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offermodels',
            name='conditions',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='offermodels',
            name='description',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='offermodels',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offermodels',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offermodels',
            name='location',
            field=models.TextField(default='Beni-Seuf'),
        ),
        migrations.AddField(
            model_name='offermodels',
            name='rev',
            field=models.BooleanField(default=False),
        ),
    ]
