# Generated by Django 4.2.2 on 2024-03-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_offerimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerimages',
            old_name='image',
            new_name='images',
        ),
    ]
