# Generated by Django 4.2.2 on 2024-03-13 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_remove_commentmodels_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodels',
            name='requests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_comments', to='accounts.request'),
        ),
    ]
